# This is a basic workflow to help you get started with Actions

name: Transcode

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out ServerDeploy repo
        uses: actions/checkout@v2
        with:
          repository: lyz05/ServerDeploy
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: master

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install rclone ffmpeg x264
          

      - name: Download video
        env:
          filename_in: gd:/Inbox/transcode
          filename_out: ./transcode
        run: |
          rclone --config ./rclone.conf copy "$filename_in" "$filename_out"
          
      - name: Transcode
        env:
          filename: ./transcode/*
        run: |
          for file in $filename
          do
              if test -f "$file"
              then
              filename_in="$file"
              filename_out="${file%.*}_ffmpeg.mp4"
              ffmpeg -i "$filename_in" -strict -2 -vcodec libx264 -preset fast -crf 28 -acodec aac -ac 2 -ar 48000 -ab 128k -f mp4 "$filename_out"
              rm "$filename_in"
              echo "$filename_in" "$filename_out"
              fi
          done

      - name: Upload video
        env:
          filename_in: ./transcode
          filename_out: gd:/Inbox/transcode
        run: |
          rclone --config ./rclone.conf copy "$filename_in" "$filename_out"
      
